In [2]:
from veggideas.load_data import load_train_data
from veggideas.load_data import load_val_data
from sklearn.dummy import DummyClassifier
import tensorflow as tf

2023-06-06 11:41:55.231354: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Found 15000 files belonging to 15 classes.


2023-06-06 11:42:05.776138: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Loading training data
Training data successfully loaded ✅
Found 3000 files belonging to 15 classes.
Loading validation data
Validation data successfully loaded ✅
Found 3000 files belonging to 15 classes.
Loading test data
Testing data successfully loaded ✅


In [3]:
train_data = load_train_data()
val_data = load_val_data()

Found 15000 files belonging to 15 classes.
Loading training data
Training data successfully loaded ✅
Found 3000 files belonging to 15 classes.
Loading validation data
Validation data successfully loaded ✅


In [5]:
def split_data(data):
    X = []
    y = []


    for images, labels in data.take(1):
        X.append(images)
        y.append(labels)
    X = tf.concat(X, axis=0)
    y = tf.concat(y, axis=0)

    return X, y

In [6]:
X_train, y_train = split_data(train_data)

In [8]:
y_train[1]

<tf.Tensor: shape=(15,), dtype=float32, numpy=
array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [ ]:


train_data.take(1)
X_train = []
y_train = []
X_val = []
y_val = []


for images, labels in train_data.take(1):
    X_train.append(images)
    y_train.append(labels)

X_train = tf.concat(X_train, axis=0)
y_train = tf.concat(y_train, axis=0)

for images, labels in val_data.take(1):
    X_val.append(images)
    y_val.append(labels)

X_val = tf.concat(X_val, axis=0)
y_val = tf.concat(y_val, axis=0)

In [30]:
y_val[1]

<tf.Tensor: shape=(15,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [33]:
def create_baseline_model(X_test, y_test, X_val, y_val):
    baseline_model = DummyClassifier(strategy='most_frequent')
    history = baseline_model.fit(X_test, y_test)
    return baseline_model

In [34]:
from sklearn.metrics import average_precision_score
baseline_model = create_baseline_model(X_train, y_train, X_val, y_val)

In [35]:
y_pred = baseline_model.predict(X_val)
average_precision_score(y_val, y_pred)

/Users/lennertverbeeck/.pyenv/versions/3.10.6/envs/veggideas/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:891: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(
/Users/lennertverbeeck/.pyenv/versions/3.10.6/envs/veggideas/lib/python3.10/site-packages/sklearn/metrics/_ranking.py:891: UserWarning: No positive class found in y_true, recall is set to one for all thresholds.
  warnings.warn(


0.06666666666666667